version: '3.8'
services:
  mysql:
    image: mysql:8.0.39
    container_name: AtendimentoMySQL
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
volumes:
  db_data:
